name: Frontend PR Discord Notification

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  Issue-Notification:
    runs-on: ubuntu-latest
    steps:
      - name: 프론트엔드 PR 생성 및 닫힘 알림 동작
        if: ${{ contains(github.event.pull_request.title, '[FE]') }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.FE_DISCORD_WEBHOOK_URL }}
          content: '[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})'
