name: Frontend Issue Discord Notification

on:
  issues:
    types: [opened, reopened]

jobs:
  Issue-Notification:
    runs-on: ubuntu-latest
    steps:
      - name: 프론트엔드 이슈 생성 알림 동작
        if: ${{ contains(github.event.issue.title, '[FE]') }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.FE_DISCORD_WEBHOOK_URL }}
          content: '[${{ github.event.issue.title }}](${{ github.event.issue.html_url }})'
